/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarmahasiswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private Boolean isUpdate = false;
    private int selectedID = -1;
    private ArrayList<Mahasiswa> listMhs;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listMhs = new ArrayList<>();
        //Dummy
        listMhs.add(new Mahasiswa("2001201", "Dodo", "A"));
        listMhs.add(new Mahasiswa("2001308", "Nana", "B"));
        listMhs.add(new Mahasiswa("2001204", "Nunu", "C"));
        // Set Table
        tabelDaftarMahasiswa.setModel(setTable());
        // Hide Delete button
        buttonDelete.setVisible(false);
    }

    public final DefaultTableModel setTable() {
        Object[] column = {"NIM", "Nama", "Nilai"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        for (int i = 0; i < listMhs.size(); i++) {
            Object[] row = new Object[3];
            row[0] = listMhs.get(i).getNim();
            row[1] = listMhs.get(i).getNama();
            row[2] = listMhs.get(i).getNilai();

            dataTabel.addRow(row);
        }

        return dataTabel;
    }

    public void insertData() {
        // Get Data
        String nim = TFNIM.getText();
        String nama = TFNama.getText();
        String nilai = TFNilai.getText();
        
        //jika data tidak lengkap (tidak ada nama atau nim atau nilai) maka data tidak dapat ditambahkan
        if (nim.isEmpty()){
            System.out.println("Insert Failed!");
            JOptionPane.showMessageDialog(null, "Data tidak berhasil ditambahkan!");
        }
        else if(nama.isEmpty()){
            System.out.println("Insert Failed!");
            JOptionPane.showMessageDialog(null, "Data tidak berhasil ditambahkan!");
        }
        else if(nilai.isEmpty()){
            System.out.println("Insert Failed!");
            JOptionPane.showMessageDialog(null, "Data tidak berhasil ditambahkan!");
        }
        else{
            listMhs.add(new Mahasiswa(nim, nama, nilai));
            //Update Table
            tabelDaftarMahasiswa.setModel(setTable());

            System.out.println("Insert Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        }
       
    }

    public void updateData() {
        // Get Data
        String nim = TFNIM.getText();
        String nama = TFNama.getText();
        String nilai = TFNilai.getText();
        
        listMhs.get(selectedID).setNim(nim);
        listMhs.get(selectedID).setNama(nama);
        listMhs.get(selectedID).setNilai(nilai);
        
        tabelDaftarMahasiswa.setModel(setTable());
        
        System.out.println("Update Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
    }

    public void deleteData() {
        // Get Data
        String nim = TFNIM.getText();
        String nama = TFNama.getText();
        String nilai = TFNilai.getText();
        
        listMhs.remove(selectedID);
        
        tabelDaftarMahasiswa.setModel(setTable());
        
        System.out.println("Delete Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        labelDaftarMahasiswa = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        TFNIM = new javax.swing.JTextField();
        labelNIM = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        labelNilai = new javax.swing.JLabel();
        TFNilai = new javax.swing.JTextField();
        ScrollPaneHome = new javax.swing.JScrollPane();
        tabelDaftarMahasiswa = new javax.swing.JTable();
        buttonDelete = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHome.setBackground(new java.awt.Color(0, 204, 204));

        labelDaftarMahasiswa.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelDaftarMahasiswa.setText("Daftar Mahasiswa");

        buttonAdd.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        TFNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNIMActionPerformed(evt);
            }
        });

        labelNIM.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        labelNIM.setText("NIM");

        labelNama.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        labelNama.setText("Nama");

        TFNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaActionPerformed(evt);
            }
        });

        labelNilai.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        labelNilai.setText("Nilai");

        TFNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNilaiActionPerformed(evt);
            }
        });

        tabelDaftarMahasiswa.setAutoCreateRowSorter(true);
        tabelDaftarMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDaftarMahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelDaftarMahasiswa.setUpdateSelectionOnSort(false);
        tabelDaftarMahasiswa.setVerifyInputWhenFocusTarget(false);
        tabelDaftarMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDaftarMahasiswaMouseClicked(evt);
            }
        });
        ScrollPaneHome.setViewportView(tabelDaftarMahasiswa);

        buttonDelete.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonCancel.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrollPaneHome, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelHomeLayout.createSequentialGroup()
                                        .addComponent(labelNama)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelHomeLayout.createSequentialGroup()
                                        .addComponent(labelNIM)
                                        .addGap(55, 55, 55)
                                        .addComponent(TFNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                                        .addComponent(labelNilai)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TFNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAdd)
                                    .addComponent(buttonDelete)
                                    .addComponent(buttonCancel)))))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(labelDaftarMahasiswa)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelDaftarMahasiswa)
                .addGap(28, 28, 28)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNIM)
                    .addComponent(buttonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama)
                    .addComponent(buttonCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNilai)
                    .addComponent(buttonDelete))
                .addGap(42, 42, 42)
                .addComponent(ScrollPaneHome, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNIMActionPerformed

    private void TFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaActionPerformed

    private void TFNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNilaiActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        if (isUpdate == false)
            insertData();
        else {
            updateData();
            buttonAdd.setText("Add");
            buttonDelete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void tabelDaftarMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDaftarMahasiswaMouseClicked
        // TODO add your handling code here:
        this.isUpdate = true;

        //Get Selected Data
        int row = tabelDaftarMahasiswa.getSelectedRow();
        String selectedNim = (tabelDaftarMahasiswa.getModel().getValueAt(row, 0).toString());
        String selectedNama = (tabelDaftarMahasiswa.getModel().getValueAt(row, 1).toString());
        String selectedNilai = (tabelDaftarMahasiswa.getModel().getValueAt(row, 2).toString());

        for (int i = 0; i < listMhs.size(); i++) {
            if (selectedNim.equals(listMhs.get(i).getNim())) {
                selectedID = i;
                break;
            }
        }

        //System.out.println(selectedID);
        TFNIM.setText(selectedNim);
        TFNama.setText(selectedNama);
        TFNilai.setText(selectedNilai);

        buttonAdd.setText("Update");
        buttonDelete.setVisible(true);
    }//GEN-LAST:event_tabelDaftarMahasiswaMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        if (isUpdate == true) {
            deleteData();
            buttonAdd.setText("Add");
            buttonDelete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        buttonAdd.setText("Add");
        buttonDelete.setVisible(false);
        this.isUpdate = false;
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneHome;
    private javax.swing.JTextField TFNIM;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFNilai;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JLabel labelDaftarMahasiswa;
    private javax.swing.JLabel labelNIM;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNilai;
    private javax.swing.JPanel panelHome;
    private javax.swing.JTable tabelDaftarMahasiswa;
    // End of variables declaration//GEN-END:variables
}
